# SPDX-FileCopyrightText: 2020 Splunk Inc.
#
# SPDX-License-Identifier: Apache-2.0

[tool.poetry]
name = "splunktaucclib"
version = "0.0.0"
description = ""
authors = ["rfaircloth-splunk <rfaircloth@splunk.com>"]
license = "APACHE-2.0"

[tool.poetry.dependencies]
python = "^3.7"
solnlib = '^4.0.0'
splunk-sdk = "^1.6"
future = "^0"
splunktalib = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest-expect = "^1.1.0"
pytest = [
    { version = "^4.6", python = "^2.7" },
    { version = "^6.0", python = "^3.7" }
]
pytest-cov = "^2"
poetry-dynamic-versioning = { version = "^0.8", python = "^3.7" }
tomlkit = "^0"
reuse = "*"
black = [
    { version = "20.8b1",  python = "^3.7" }
]

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"